baseURL = "https://amdjml.com/"
languageCode = "en-us"
title = "Ahmad Jamali"
theme = "cactus"
copyright = "Ahmad Jamali"
googleAnalytics= "G-83YRRQSTEN"
googleAnalyticsAsync = true

[[menu.main]]
   name = "Home"
   url = "/"
   weight = 1

[[menu.main]]
   name = "Writings"
   url = "/posts"
   weight = 2

[[menu.main]]
   name = "Tags"
   url = "/tags"
   weight = 3

[[menu.main]]
   name = "About"
   url = "/about"
   weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]
   colortheme = "white"
   rss = true
   googleAnalyticsAsync = true 
   showAllPostsArchive = false 

   description = "A systems administrator's blog from Northern Virginia."
   mainSection = "posts"
   showAllPostsOnHomePage = false
   postsOnHomePage = 5
   tagsOverview = false

   dateFormat = "2006-01-02" 

   show_updated = true 
   showReadTime = true 
  
   [params.comments]
     enabled = true 
     engine = "utterances" 
     [params.comments.utterances]
       repo = "amdjml/amdjml.github.io"
       theme = "preferred-color-scheme"

[[params.social]]
   name = "github"
   link = "https://github.com/amdjml"

[[params.social]]
   name = "email"
   link = "hello@amdjml.com" 

[[params.social]]
   name = "linkedin"
   link = "https://www.linkedin.com/in/ahmadjamali"
